hda_forum/automation/urls.py
from django.urls import path
from automation import views
app_name='automation'


urlpatterns=[
	#Desg Automation url
	path('desg_automation/', views.desg_automation,name='desg_automation'),
	path('desg_automation_update/',views.desg_automation_update, name='desg_automation_update'),
	path('desg_automation/<id>/edit/', views.edit_desg_automation_content,name='edit_desg_automation_content'),
    path('desg_automation/<id>/delete/', views.delete_desg_automation_content,name='delete_desg_automation_content'),
	path('desg_automation_update/<id>/edit/', views.edit_desg_automation_update,name='edit_desg_automation_update'),
	path('desg_automation_update/<id>/delete/', views.delete_desg_automation_update,name='delete_desg_automation_update'),

	#Pdc Automation Url
	path('pdc_automation/', views.pdc_automation,name='pdc_automation'),
	path('pdc_automation_update/',views.pdc_automation_update, name='pdc_automation_update'),
	path('pdc_automation/<id>/edit/', views.edit_pdc_automation_content,name='edit_pdc_automation_content'),
    path('pdc_automation/<id>/delete/', views.delete_pdc_automation_content,name='delete_pdc_automation_content'),
	path('pdc_automation_update/<id>/edit/', views.edit_pdc_automation_update,name='edit_pdc_automation_update'),
	path('pdc_automation_update/<id>/delete/', views.delete_pdc_automation_update,name='delete_pdc_automation_update'),

	#Ldm Automation Url
	path('ldm_automation/', views.ldm_automation,name='ldm_automation'),
	path('ldm_automation_update/', views.ldm_automation_update, name='ldm_automation_update'),
	path('ldm_automation/<id>/edit/', views.edit_ldm_automation_content,name='edit_ldm_automation_content'),
    path('ldm_automation/<id>/delete/', views.delete_ldm_automation_content,name='delete_ldm_automation_content'),
	path('ldm_automation_update/<id>/edit/', views.edit_ldm_automation_update,name='edit_ldm_automation_update'),
	path('ldm_automation_update/<id>/delete/', views.delete_ldm_automation_update,name='delete_ldm_automation_update'),
]

hda_forum/desg_t18/urls.py
from django.urls import path
from desg_t18 import views
app_name='desg_t18'

urlpatterns=[
    #test
    path('test/',views.test, name='test'),
    #validate user
    path('login/', views.login, name='login'),
    path('register/', views.register, name='register'),
    path('reset_password/', views.reset_pass, name='change_pass'),
    #hda home
    path('home/', views.hda_home, name='hda_home'),
    path('team_view/', views.team_view, name='team_view'),
    #desg home
    path('desg_home/',views.desg_home, name='desg_home'),
    path('desg_team/',views.desg_team, name='desg_team'),
    #pc
    path('perform_check/',views.perform_check, name='pc'),
    path('pc_update/',views.pc_update, name='pc_update'),
    path('pc_update/<id>/edit/',views.edit_pc_update, name='edit_pc_update'),
    path('pc_update/<id>/delete/', views.delete_pc_update,name='delete_pc_update'),
    #gml
    path('gml_creation/',views.gml_creation, name='gml'),
    path('gml_update/',views.gml_update, name='gml_update'),
    path('gml_update/<id>/edit/',views.edit_gml_update, name='edit_gml_update'),
    path('gml_update/<id>/delete/', views.delete_gml_update,name='delete_gml_update'),
    #triage updates
    path('triage_update/',views.triage_update, name='triage_update'),
    path('triage_update/<id>/edit/',views.edit_triage_content, name='edit_triage_content'),
    path('triage_update/<id>/delete/', views.delete_triage_content,name='delete_triage_content'),
    #meeting update
    path('meeting_update/',views.meeting_update, name='meeting_update'),
    path('meeting_update/<id>/edit/', views.edit_meeting_content,name='edit_meeting_content'),
    path('meeting_update/<id>/delete/', views.delete_meeting_content,name='delete_meeting_content'),
    #forum updates
    path('forum/',views.forum, name='forum'),
    path('forum/<id>/edit/', views.edit_forum_content,name='edit_forum_content'),
    path('forum/<id>/delete/', views.delete_forum_content,name='delete_forum_content'),
    #dashboard
    path('desg_dashboard/', views.desg_dashboard,name='desg_dashboard'),
    path('hda_dashboard/',views.hda_dashboard, name='hda_dashboard'),
    
    
]

hda_forum/hda_forum/urls.py
"""hda_forum URL Configuration

The `urlpatterns` list routes URLs to views. For more information please see:
    https://docs.djangoproject.com/en/2.0/topics/http/urls/
"""
from django.contrib import admin
from django.urls import path,include
from django.conf import settings
from django.conf.urls.static import static
from desg_t18 import views
from desg_t18 import urls as desg_app
from automation import urls as automation_app
from pdc import urls as pdc_app
from ldm import urls as ldm_app

app_name='hda_forum'
urlpatterns = [
    path('', views.index, name='index'),
    path('pdc/', include(pdc_app)),
    path('desg/', include(desg_app)),
    path('ldm/', include(ldm_app)),
    path('automation/', include(automation_app)),
    path('admin/', admin.site.urls),


]

if settings.DEBUG:
    urlpatterns+= static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
    urlpatterns+= static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

hda_forum/ldm/urls.py
from django.urls import path
from ldm import views
app_name='ldm'

urlpatterns=[
    #pdc home
    path('ldm_home/',views.ldm_home, name='ldm_home'),
    path('ldm_team/',views.ldm_team, name='ldm_team'),
    path('ldm_workflow/',views.ldm_workflow, name='ldm_workflow'),
    #meeting update
    path('ldm_meeting_update/',views.ldm_meeting_update, name='ldm_meeting_update'),
    path('meeting_update/<id>/edit/', views.edit_meeting_content,name='edit_meeting_content'),
    path('meeting_update/<id>/delete/', views.delete_meeting_content,name='delete_meeting_content'),
    #forum updates
    path('ldm_forum/',views.ldm_forum, name='ldm_forum'),
    path('ldm_forum/<id>/edit/', views.edit_forum_content,name='edit_forum_content'),
    path('ldm_forum/<id>/delete/', views.delete_forum_content,name='delete_forum_content'),
    #dashboard
    path('ldm_dashboard/', views.ldm_dashboard,name='ldm_dashboard'),
    
    
]

hda_forum/automation/views.py
from django.shortcuts import render,redirect, get_object_or_404
from django.http import JsonResponse
from django.db.models import Q
from django.core.paginator import Paginator, EmptyPage, PageNotAnInteger
from automation.models import (
                            DesgAutomationRelease,
                            DesgAutomationUpdate,
                            PdcAutomationUpdate,
                            PdcAutomationRelease,
                            LdmAutomationUpdate,
                            LdmAutomationRelease,
                            )
from automation.automationForm import (
                                DesgAutomationUpdateForm,
                                DesgAutomationReleaseNoteForm,
                                PdcAutomationUpdateForm,
                                PdcAutomationReleaseNoteForm,
                                LdmAutomationUpdateForm,
                                LdmAutomationReleaseNoteForm,
                                )
'''
DESG Autoamtion view
'''
def desg_automation(request):
    desg_automation_content=DesgAutomationRelease.objects.all()
    query=request.GET.get('search')
    desg_automation_form=DesgAutomationReleaseNoteForm(request.POST or None)
    if query:
        desg_automation_content=desg_automation_content.filter(
                                    Q(title__icontains=query)|
                                    Q(content__icontains=query)
                                    )
    if request.method =='POST':
        if desg_automation_form.is_valid():
            meeting=desg_automation_form.save(commit=False)
            meeting.updated_by=request.session['user']
            meeting.save()
            return redirect('/automation/desg_automation')
    else:
        paginator = Paginator(desg_automation_content, 10) # Show 2 contacts per page
        page = request.GET.get('page')
        post = paginator.get_page(page)
        automation_content={"desg_automation_form":desg_automation_form,
                "posted_data":post,
                }
    return render(request,'automation/desg/desg_Automation.html',automation_content)

def desg_automation_update(request):
    desg_automation_update=DesgAutomationUpdate.objects.all()
    query=request.GET.get('search')
    desg_automation_update_form=DesgAutomationUpdateForm(request.POST or None)
    if query:
        desg_automation_update=desg_automation_update.filter(
                                    Q(title__icontains=query)|
                                    Q(content__icontains=query)
                                    )
    if request.method =='POST':
        if desg_automation_update_form.is_valid():
            meeting=desg_automation_update_form.save(commit=False)
            meeting.updated_by=request.session['user']
            meeting.save()
            return redirect('/automation/desg_automation_update')
    else:
        paginator = Paginator(desg_automation_update, 10) # Show 2 contacts per page
        page = request.GET.get('page')
        post = paginator.get_page(page)
        desg_automation_content={"desg_automation_update_form":desg_automation_update_form,
                "posted_data":post,
                }
    return render(request,'automation/desg/desg_automation_update.html',desg_automation_content)

def edit_desg_automation_content(request,id=None):
    instance=get_object_or_404(DesgAutomationRelease,id=id)
    meeting_form=DesgAutomationReleaseNoteForm(request.POST or None, instance=instance)
    meeting={"meeting_form":meeting_form,
                "posted_data":instance,
                }
    if meeting_form.is_valid():
        meeting=meeting_form.save(commit=False)
        meeting.updated_by=request.session['user']
        meeting.save()
        return redirect('/automation/desg_automation')
    else:
        return render(request,'automation/desg/edit_desg_automation.html',meeting)

def delete_desg_automation_content(request, id=None):
    instance=get_object_or_404(DesgAutomationRelease,id=id)
    instance.delete()
    return redirect('/automation/desg_automation')

def edit_desg_automation_update(request,id=None):
    instance=get_object_or_404(DesgAutomationUpdate,id=id)
    meeting_form=DesgAutomationUpdateForm(request.POST or None, instance=instance)
    meeting={"meeting_form":meeting_form,
                "posted_data":instance,
                }
    if meeting_form.is_valid():
        meeting=meeting_form.save(commit=False)
        meeting.updated_by=request.session['user']
        meeting.save()
        return redirect('/automation/desg_automation_update')
    else:
        return render(request,'automation/desg/edit_desg_automation_update.html',meeting)

def delete_desg_automation_update(request, id=None):
    instance=get_object_or_404(DesgAutomationUpdate,id=id)
    instance.delete()
    return redirect('/automation/desg_automation_update')

'''
PDC Automation View
'''

def pdc_automation(request):
    pdc_automation_content=PdcAutomationRelease.objects.all()
    query=request.GET.get('search')
    pdc_automation_form=PdcAutomationReleaseNoteForm(request.POST or None)
    if query:
        pdc_automation_content=pdc_automation_content.filter(
                                    Q(title__icontains=query)|
                                    Q(content__icontains=query)
                                    )
    if request.method =='POST':
        if pdc_automation_form.is_valid():
            meeting=pdc_automation_form.save(commit=False)
            meeting.updated_by=request.session['user']
            meeting.save()
            return redirect('/automation/pdc_automation')
    else:
        paginator = Paginator(pdc_automation_content, 10) # Show 2 contacts per page
        page = request.GET.get('page')
        post = paginator.get_page(page)
        automation_content={"pdc_automation_form":pdc_automation_form,
                "posted_data":post,
                }
    return render(request,'automation/pdc/pdc_Automation.html',automation_content)

def pdc_automation_update(request):
    pdc_automation_update=PdcAutomationUpdate.objects.all()
    query=request.GET.get('search')
    pdc_automation_update_form=PdcAutomationUpdateForm(request.POST or None)
    if query:
        pdc_automation_update=pdc_automation_update.filter(
                                    Q(title__icontains=query)|
                                    Q(content__icontains=query)
                                    )
    if request.method =='POST':
        if pdc_automation_update_form.is_valid():
            meeting=pdc_automation_update_form.save(commit=False)
            meeting.updated_by=request.session['user']
            meeting.save()
            return redirect('/automation/pdc_automation_update')
    else:
        paginator = Paginator(pdc_automation_update, 10) # Show 2 contacts per page
        page = request.GET.get('page')
        post = paginator.get_page(page)
        pdc_automation_content={"pdc_automation_update_form":pdc_automation_update_form,
                "posted_data":post,
                }
    return render(request,'automation/pdc/pdc_automation_update.html',pdc_automation_content)

def edit_pdc_automation_content(request,id=None):
    instance=get_object_or_404(PdcAutomationRelease,id=id)
    meeting_form=PdcAutomationReleaseNoteForm(request.POST or None, instance=instance)
    meeting={"meeting_form":meeting_form,
                "posted_data":instance,
                }
    if meeting_form.is_valid():
        meeting=meeting_form.save(commit=False)
        meeting.updated_by=request.session['user']
        meeting.save()
        return redirect('/automation/pdc_automation')
    else:
        return render(request,'automation/pdc/edit_pdc_automation.html',meeting)

def delete_pdc_automation_content(request, id=None):
    instance=get_object_or_404(PdcAutomationRelease,id=id)
    instance.delete()
    return redirect('/automation/pdc_automation')

def edit_pdc_automation_update(request,id=None):
    instance=get_object_or_404(PdcAutomationUpdate,id=id)
    meeting_form=PdcAutomationUpdateForm(request.POST or None, instance=instance)
    meeting={"meeting_form":meeting_form,
                "posted_data":instance,
                }
    if meeting_form.is_valid():
        meeting=meeting_form.save(commit=False)
        meeting.updated_by=request.session['user']
        meeting.save()
        return redirect('/automation/pdc_automation_update')
    else:
        return render(request,'automation/pdc/edit_pdc_automation_update.html',meeting)

def delete_pdc_automation_update(request, id=None):
    instance=get_object_or_404(PdcAutomationUpdate,id=id)
    instance.delete()
    return redirect('/automation/pdc_automation_update')



'''
LDM Automation View
'''

def ldm_automation(request):
    ldm_automation_content=LdmAutomationRelease.objects.all()
    query=request.GET.get('search')
    ldm_automation_form=LdmAutomationReleaseNoteForm(request.POST or None)
    if query:
        ldm_automation_content=ldm_automation_content.filter(
                                    Q(title__icontains=query)|
                                    Q(content__icontains=query)
                                    )
    if request.method =='POST':
        if ldm_automation_form.is_valid():
            meeting=ldm_automation_form.save(commit=False)
            meeting.updated_by=request.session['user']
            meeting.save()
            return redirect('/automation/ldm_automation')
    else:
        paginator = Paginator(ldm_automation_content, 10) # Show 2 contacts per page
        page = request.GET.get('page')
        post = paginator.get_page(page)
        automation_content={"ldm_automation_form":ldm_automation_form,
                "posted_data":post,
                }
    return render(request,'automation/ldm/ldm_Automation.html',automation_content)

def ldm_automation_update(request):
    ldm_automation_update=LdmAutomationUpdate.objects.all()

hda_forum/templates/automation/desg/desg_Automation.html
{% extends "base.html" %}
{% load crispy_forms_tags %}
{% load static %}
{% block page %}
    {{ desg_automation_form.media }}
{% endblock page %}

{% block body %}

  <div class="row" style="background:inherit">
<div class="col-lg-12">
  <nav class="navbar navbar-default bg nav-custom" style="z-index:10">
    <div class="container logout">
      <ul class="nav navbar-nav navbar-right log-bg">
        <li><a href="http://127.0.0.1:8000/"><span class="glyphicon glyphicon-user"></span>Logout</a></li>
      </ul>
      <form class="navbar-form navbar-right" role="search">
                <div class="input-group">
                    <input class=" form-control" type="text" name="forum-search" placeholder="Search here">
                    <span class="input-group-btn">
                        <button type="submit" class="btn btn-default">
                            <span class="glyphicon glyphicon-search"></span>
                        </button>
                    </span>
                </div>
            </form>
    </div>
  </nav>
</div>
</div>
<br><br><br>
<div class="row">
  <div class="col-md-2">
    <div class="collapse navbar-collapse navbar-ex1-collapse">
        <ul class="nav navbar-nav side-nav">
          <li>
              <a href="{% url 'desg_t18:desg_home' %}"><i class="glyphicon glyphicon-home"></i>  DESG Home</a>
          </li>
          <li>
            <a href="#" data-toggle="collapse" data-target="#submenu-1"><i class="fa fa-fw fa-star"></i> DESG Work flow<i class="fa fa-fw fa-angle-down pull-right"></i></a>
              <ul id="submenu-1" class="collapse">
                  <li><a href="{% url 'desg_t18:pc' %}"><i class="fa fa-angle-double-right"></i> Perform check</a></li>
                  <li><a href="{% url 'desg_t18:gml' %}"><i class="fa fa-angle-double-right"></i> GML Creation</a></li>
              </ul>
          </li>
          <li>
            <a href="#" data-toggle="collapse" data-target="#submenu-2"><i class="fa fa-fw fa-star"></i>  Discustions <i class="fa fa-fw fa-angle-down pull-right"></i></a>
            <ul id="submenu-2" class="collapse">
              <li><a href="{% url 'desg_t18:triage_update' %}"><i class="fa fa-angle-double-right"></i> Triage Note</a></li>
              <li><a href="{% url 'desg_t18:meeting_update' %}"><i class="fa fa-angle-double-right"></i>Meeting updates</a></li>
            </ul>
          </li>
          <li>
            <a href="#" data-toggle="collapse" data-target="#submenu-3"><i class="fa fa-fw fa-star"></i>DESG Automation <i class="fa fa-fw fa-angle-down pull-right"></i></a>
            <ul id="submenu-3" class="collapse">
              <li><a href="{% url 'automation:desg_automation' %}"><i class="fa fa-angle-double-right"></i> Tool release Note</a></li>
              <li><a href="{% url 'automation:desg_automation_update' %}"><i class="fa fa-angle-double-right"></i>Tool requirment Update</a></li>
            </ul>
          </li>
              <li>
                  <a href="{% url 'desg_t18:desg_dashboard' %}"><i class="fa fa-fw fa-star"></i>DESG Dashboard</a>
              </li>
              <li>
                  <a href="{% url 'desg_t18:forum' %}"><i class="glyphicon glyphicon-book"></i>  Forum</a>
              </li>

        </ul>
        </div>
  </div>
  <div class="col-md-10" >
    <div class="container">
      <h3 class="head">DESG Automation</h3>
      <div class="jumbotron jumb">
        <p class="paragraph">
        DESG Team using different tools for to validate the design.
      </p>
      <ol>
        <li>RPA Tool</li>
        <li>T18 Validation tool</li>
        <li>MPS Boundary extraction tool</li>
        <li>T18 Vs PNI Loc id comparsion tool</li>
      </ol>

      <h4 class="head">RPA Tool</h4>
      <p class="paragraph">
        RPA is the Robotic tool which do all the Design validation checks in T18 file and also create feedback register with all the validations results. including downloading required input files from NBN share point locations.
      </p>
      <h4 class="head">RPA Tool Activitys</h4>
      <ol>
        <li>Download and export required files from sharepoint location and PNI (T18, Design export from PNI and NDD Document)</li>
        <li>T18 Vs PNI boundary comparison (mapbasic script triggered by RPA)</li>
        <li>T18 Trimming (mapbasic script triggered by RPA)</li>
        <li>T18 Validation and fix (mapbasic script triggered by RPA)</li>
        <li>FBR Generations (macro script triggered by RPA)</li>
      </ol>
      <h4 class="head">MPS Boundary extraction tool</h4>
      <p class="paragraph">
        this is mapbasic script which will extract ony MPS boundary from boundary table with specific technology type and make specific format which accept in PNI import tool. this tool need to be triggered manually.
      </p>
      <h4 class="head">T18 Vs PNI Loc id comparsion tool</h4>
      <p class="paragraph">
        This tool compare SLs with in MPS are served by GTD and GTD where is located. for idealy GTD and PCD are should be in MPS boundary in PNI. if PCD located outside MPS this tool will capture those locations and give summary csv file.
      </p>
      </div>
    </div>




    <div class="container">
      <h3 class="head text-center">DESG Tool Release Updates</h3>
      {% for post in posted_data %}
        <div class="jumbotron jumb">

        <h3 class="head meeting-content">{{ post.title }} <small>{{ post.updated_date|timesince }}</small></h3>
        <p class="meeting-p">{{  post.content }}</p>
        <p class="meeting-u">Updated by {{ post.updated_by }} on {{ post.updated_date}}</p>
        <br>
        <a class="btn btn-primary" href="{% url 'automation:edit_desg_automation_content' id=post.id %}">Edit</a>
        <a class="btn btn-primary" href="{% url 'automation:delete_desg_automation_content' id=post.id %}">Delete</a>
      </div>
      {% endfor %}
      <br><br>
      <!-- pagination goes here  -->
        <br><br>
        <div class="pagination">
          <span class="step-links">
              {% if posted_data.has_previous %}
                  <a href="?page=1">&laquo; first</a>
                  <a href="?page={{ posted_data.previous_page_number }}">previous</a>
              {% endif %}
          <span class="current">
            Page {{ posted_data.number }} of {{ posted_data.paginator.num_pages }}.
         </span>
            {% if posted_data.has_next %}
              <a href="?page={{ posted_data.next_page_number }}">next</a>
              <a href="?page={{ posted_data.paginator.num_pages }}">last &raquo;</a>
            {% endif %}
         </span>
       </div>

      <div class="jumbotron jumb">
      <form method="post">
      {% csrf_token %}
      {{desg_automation_form|crispy}}

      <input class="btn btn-default btn-primary" type="submit" name="Submit">
      </form>
      </div>



  </div>
  </div>
</div>

{% endblock %}

hda_forum/templates/automation/desg/desg_automation_update.html
{% extends "base.html" %}

{% load crispy_forms_tags %}
{% load static %}
{% block page %}
    {{ desg_automation_update_form.media }}
{% endblock page %}
{% block body %}

  <div class="row" style="background:inherit">
<div class="col-lg-12">
  <nav class="navbar navbar-default bg nav-custom" style="z-index:10">
    <div class="container logout">
      <ul class="nav navbar-nav navbar-right log-bg">
        <li><a href="http://127.0.0.1:8000/"><span class="glyphicon glyphicon-user"></span>Logout</a></li>
      </ul>
      <form class="navbar-form navbar-right" role="search">
                <div class="input-group">
                    <input class=" form-control" type="text" name="forum-search" placeholder="Search here">
                    <span class="input-group-btn">
                        <button type="submit" class="btn btn-default">
                            <span class="glyphicon glyphicon-search"></span>
                        </button>
                    </span>
                </div>
            </form>
    </div>
  </nav>
</div>
</div>
<br><br><br>
  <div class="row">
  <div class="col-md-2">
    <div class="collapse navbar-collapse navbar-ex1-collapse">
        <ul class="nav navbar-nav side-nav">
          <li>
              <a href="{% url 'desg_t18:desg_home' %}"><i class="glyphicon glyphicon-home"></i>  DESG Home</a>
          </li>
          <li>
            <a href="#" data-toggle="collapse" data-target="#submenu-1"><i class="fa fa-fw fa-star"></i> DESG Work flow<i class="fa fa-fw fa-angle-down pull-right"></i></a>
              <ul id="submenu-1" class="collapse">
                  <li><a href="{% url 'desg_t18:pc' %}"><i class="fa fa-angle-double-right"></i> Perform check</a></li>
                  <li><a href="{% url 'desg_t18:gml' %}"><i class="fa fa-angle-double-right"></i> GML Creation</a></li>
              </ul>
          </li>
          <li>
            <a href="#" data-toggle="collapse" data-target="#submenu-2"><i class="fa fa-fw fa-star"></i>  Discustions <i class="fa fa-fw fa-angle-down pull-right"></i></a>
            <ul id="submenu-2" class="collapse">
              <li><a href="{% url 'desg_t18:triage_update' %}"><i class="fa fa-angle-double-right"></i> Triage Note</a></li>
              <li><a href="{% url 'desg_t18:meeting_update' %}"><i class="fa fa-angle-double-right"></i>Meeting updates</a></li>
            </ul>
          </li>
          <li>
            <a href="#" data-toggle="collapse" data-target="#submenu-3"><i class="fa fa-fw fa-star"></i>DESG Automation <i class="fa fa-fw fa-angle-down pull-right"></i></a>
            <ul id="submenu-3" class="collapse">
              <li><a href="{% url 'automation:desg_automation' %}"><i class="fa fa-angle-double-right"></i> Tool release Note</a></li>
              <li><a href="{% url 'automation:desg_automation_update' %}"><i class="fa fa-angle-double-right"></i>Tool requirment Update</a></li>
            </ul>
          </li>
              <li>
                  <a href="{% url 'desg_t18:desg_dashboard' %}"><i class="fa fa-fw fa-star"></i>DESG Dashboard</a>
              </li>
              <li>
                  <a href="{% url 'desg_t18:forum' %}"><i class="glyphicon glyphicon-book"></i>  Forum</a>
              </li>

        </ul>
  </div>
</div>
  <div class="col-md-10" >
    <div class="container">

      <h3 class="head text-center">DESG Tool Requirment Updates</h3>



      {% for post in posted_data %}
        <div class="jumbotron jumb">

        <h3 class="head meeting-content">{{ post.title }} <small>{{ post.updated_date|timesince }}</small></h3>
        <p class="meeting-p">{{ post.content|linebreaks }}</p>
        <p class="meeting-u">Updated by {{ post.updated_by }} on {{ post.updated_date}}</p>
        <br>
        <a class="btn btn-primary" href="{% url 'automation:edit_desg_automation_update' id=post.id %}">Edit</a>
        <a class="btn btn-primary" href="{% url 'automation:delete_desg_automation_update' id=post.id %}">Delete</a>
      </div>
      {% endfor %}
      <br><br>
      <!-- pagination goes here  -->
        <br><br>
        <div class="pagination">
          <span class="step-links">
              {% if posted_data.has_previous %}
                  <a href="?page=1">&laquo; first</a>
                  <a href="?page={{ posted_data.previous_page_number }}">previous</a>
              {% endif %}
          <span class="current">
            Page {{ posted_data.number }} of {{ posted_data.paginator.num_pages }}.
         </span>
            {% if posted_data.has_next %}
              <a href="?page={{ posted_data.next_page_number }}">next</a>
              <a href="?page={{ posted_data.paginator.num_pages }}">last &raquo;</a>
            {% endif %}
         </span>
       </div>

      <div class="jumbotron jumb">
      <form method="post">
      {% csrf_token %}
      {{desg_automation_update_form|crispy}}

      <input class="btn btn-default btn-primary" type="submit" name="Submit">
      </form>
      </div>



  </div>
  </div>
</div>

{% endblock %}