hda_forum/automation/urls.py
from django.urls import path
from automation import views
app_name='automation'


urlpatterns=[
	#Desg Automation url
	path('desg_automation/', views.desg_automation,name='desg_automation'),
	path('desg_automation_update/',views.desg_automation_update, name='desg_automation_update'),
	path('desg_automation/<id>/edit/', views.edit_desg_automation_content,name='edit_desg_automation_content'),
    path('desg_automation/<id>/delete/', views.delete_desg_automation_content,name='delete_desg_automation_content'),
	path('desg_automation_update/<id>/edit/', views.edit_desg_automation_update,name='edit_desg_automation_update'),
	path('desg_automation_update/<id>/delete/', views.delete_desg_automation_update,name='delete_desg_automation_update'),

	#Pdc Automation Url
	path('pdc_automation/', views.pdc_automation,name='pdc_automation'),
	path('pdc_automation_update/',views.pdc_automation_update, name='pdc_automation_update'),
	path('pdc_automation/<id>/edit/', views.edit_pdc_automation_content,name='edit_pdc_automation_content'),
    path('pdc_automation/<id>/delete/', views.delete_pdc_automation_content,name='delete_pdc_automation_content'),
	path('pdc_automation_update/<id>/edit/', views.edit_pdc_automation_update,name='edit_pdc_automation_update'),
	path('pdc_automation_update/<id>/delete/', views.delete_pdc_automation_update,name='delete_pdc_automation_update'),

	#Ldm Automation Url
	path('ldm_automation/', views.ldm_automation,name='ldm_automation'),
	path('ldm_automation_update/', views.ldm_automation_update, name='ldm_automation_update'),
	path('ldm_automation/<id>/edit/', views.edit_ldm_automation_content,name='edit_ldm_automation_content'),
    path('ldm_automation/<id>/delete/', views.delete_ldm_automation_content,name='delete_ldm_automation_content'),
	path('ldm_automation_update/<id>/edit/', views.edit_ldm_automation_update,name='edit_ldm_automation_update'),
	path('ldm_automation_update/<id>/delete/', views.delete_ldm_automation_update,name='delete_ldm_automation_update'),
]

hda_forum/desg_t18/urls.py
from django.urls import path
from desg_t18 import views
app_name='desg_t18'

urlpatterns=[
    #test
    path('test/',views.test, name='test'),
    #validate user
    path('login/', views.login, name='login'),
    path('register/', views.register, name='register'),
    path('reset_password/', views.reset_pass, name='change_pass'),
    #hda home
    path('home/', views.hda_home, name='hda_home'),
    path('team_view/', views.team_view, name='team_view'),
    #desg home
    path('desg_home/',views.desg_home, name='desg_home'),
    path('desg_team/',views.desg_team, name='desg_team'),
    #pc
    path('perform_check/',views.perform_check, name='pc'),
    path('pc_update/',views.pc_update, name='pc_update'),
    path('pc_update/<id>/edit/',views.edit_pc_update, name='edit_pc_update'),
    path('pc_update/<id>/delete/', views.delete_pc_update,name='delete_pc_update'),
    #gml
    path('gml_creation/',views.gml_creation, name='gml'),
    path('gml_update/',views.gml_update, name='gml_update'),
    path('gml_update/<id>/edit/',views.edit_gml_update, name='edit_gml_update'),
    path('gml_update/<id>/delete/', views.delete_gml_update,name='delete_gml_update'),
    #triage updates
    path('triage_update/',views.triage_update, name='triage_update'),
    path('triage_update/<id>/edit/',views.edit_triage_content, name='edit_triage_content'),
    path('triage_update/<id>/delete/', views.delete_triage_content,name='delete_triage_content'),
    #meeting update
    path('meeting_update/',views.meeting_update, name='meeting_update'),
    path('meeting_update/<id>/edit/', views.edit_meeting_content,name='edit_meeting_content'),
    path('meeting_update/<id>/delete/', views.delete_meeting_content,name='delete_meeting_content'),
    #forum updates
    path('forum/',views.forum, name='forum'),
    path('forum/<id>/edit/', views.edit_forum_content,name='edit_forum_content'),
    path('forum/<id>/delete/', views.delete_forum_content,name='delete_forum_content'),
    #dashboard
    path('desg_dashboard/', views.desg_dashboard,name='desg_dashboard'),
    path('hda_dashboard/',views.hda_dashboard, name='hda_dashboard'),
    
    
]

hda_forum/hda_forum/urls.py
"""hda_forum URL Configuration

The `urlpatterns` list routes URLs to views. For more information please see:
    https://docs.djangoproject.com/en/2.0/topics/http/urls/
"""
from django.contrib import admin
from django.urls import path,include
from django.conf import settings
from django.conf.urls.static import static
from desg_t18 import views
from desg_t18 import urls as desg_app
from automation import urls as automation_app
from pdc import urls as pdc_app
from ldm import urls as ldm_app

app_name='hda_forum'
urlpatterns = [
    path('', views.index, name='index'),
    path('pdc/', include(pdc_app)),
    path('desg/', include(desg_app)),
    path('ldm/', include(ldm_app)),
    path('automation/', include(automation_app)),
    path('admin/', admin.site.urls),


]

if settings.DEBUG:
    urlpatterns+= static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
    urlpatterns+= static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

hda_forum/ldm/urls.py
from django.urls import path
from ldm import views
app_name='ldm'

urlpatterns=[
    #pdc home
    path('ldm_home/',views.ldm_home, name='ldm_home'),
    path('ldm_team/',views.ldm_team, name='ldm_team'),
    path('ldm_workflow/',views.ldm_workflow, name='ldm_workflow'),
    #meeting update
    path('ldm_meeting_update/',views.ldm_meeting_update, name='ldm_meeting_update'),
    path('meeting_update/<id>/edit/', views.edit_meeting_content,name='edit_meeting_content'),
    path('meeting_update/<id>/delete/', views.delete_meeting_content,name='delete_meeting_content'),
    #forum updates
    path('ldm_forum/',views.ldm_forum, name='ldm_forum'),
    path('ldm_forum/<id>/edit/', views.edit_forum_content,name='edit_forum_content'),
    path('ldm_forum/<id>/delete/', views.delete_forum_content,name='delete_forum_content'),
    #dashboard
    path('ldm_dashboard/', views.ldm_dashboard,name='ldm_dashboard'),
    
    
]

hda_forum/pdc/urls.py
from django.urls import path
from pdc import views
app_name='pdc'

urlpatterns=[
    #pdc home
    path('pdc_home/',views.pdc_home, name='pdc_home'),
    path('pdc_team/',views.pdc_team, name='pdc_team'),
    path('pdc_workflow/',views.pdc_workflow, name='pdc_workflow'),

   
    #meeting update
    path('pdc_meeting_update/',views.meeting_update, name='pdc_meeting_update'),
    path('meeting_update/<id>/edit/', views.edit_meeting_content,name='edit_meeting_content'),
    path('meeting_update/<id>/delete/', views.delete_meeting_content,name='delete_meeting_content'),
    #forum updates
    path('pdc_forum/',views.pdc_forum, name='pdc_forum'),
    path('pdc_forum/<id>/edit/', views.edit_forum_content,name='edit_forum_content'),
    path('pdc_forum/<id>/delete/', views.delete_forum_content,name='delete_forum_content'),
    #dashboard
    path('pdc_dashboard/', views.pdc_dashboard,name='pdc_dashboard'),
    
    
]

hda_forum/ldm/models.py
from django.db import models

# Create your models here.

class LdmForum(models.Model):
    track=models.CharField(max_length=50,blank=True)
    title=models.CharField(max_length=500,blank=True)
    question=models.CharField(max_length=500,blank=True)
    answer=models.TextField(max_length=5000,blank=True)
    updated_date=models.DateTimeField(auto_now=True)
    updated_by=models.CharField(max_length=50,blank=True)

    def __str__(self):
        return self.question

class LdmMeetingUpdate(models.Model):
    title=models.CharField(max_length=100)
    content=models.TextField(max_length=2000)
    updated_date=models.DateTimeField(auto_now=True)
    updated_by=models.CharField(max_length=50,blank=True)

    def __str__(self):
        return self.title

hda_forum/ldm/views.py
from django.shortcuts import render,redirect, get_object_or_404
import datetime
from django.http import JsonResponse
from django.db.models import Q
from django.core.paginator import Paginator, EmptyPage, PageNotAnInteger
from desg_t18 import dash
from ldm.ldm_form import LdmMeetingUpdateForm, LdmForumForm
from ldm.models import (
                            LdmMeetingUpdate,
                            LdmForum,
                            )
# Create your views here.

def ldm_team(request):

    return render(request, 'ldm/ldm_team.html')

def ldm_home(request,track=None):
    user=request.session['user']
    print ("im the logged user",user)
    return render(request,'ldm/ldmhome.html',{})

def ldm_workflow(request):

    return render(request, 'ldm/ldm_workflow.html')

def ldm_meeting_update(request,track=None):
    meeting_update=LdmMeetingUpdate.objects.all()
    query=request.GET.get('search')
    meeting_form=LdmMeetingUpdateForm(request.POST or None)
    if query:
        meeting_update=meeting_update.filter(
                                    Q(title__icontains=query)|
                                    Q(content__icontains=query)
                                    )
    if request.method =='POST':
        if meeting_form.is_valid():
            meeting=meeting_form.save(commit=False)
            meeting.updated_by=request.session['user']
            meeting.save()
            return redirect('/ldm/ldm_meeting_update')
    else:
        paginator = Paginator(meeting_update, 10) # Show 2 contacts per page
        page = request.GET.get('page')
        post = paginator.get_page(page)
        meeting={"meeting_form":meeting_form,
                "posted_data":post,
                }
        return render(request,'ldm/ldm_meetingupdates.html',meeting)

def edit_meeting_content(request,id=None):
    instance=get_object_or_404(LdmMeetingUpdate,id=id)
    meeting_form=LdmMeetingUpdateForm(request.POST or None, instance=instance)
    meeting={"meeting_form":meeting_form,
                "posted_data":instance,
                }
    if meeting_form.is_valid():
        meeting=meeting_form.save(commit=False)
        meeting.updated_by=request.session['user']
        meeting.save()
        return redirect('/ldm/ldm_meeting_update')
    else:
        return render(request,'ldm/editMeetingcontent.html',meeting)

def delete_meeting_content(request, id=None):
    instance=get_object_or_404(LdmMeetingUpdate,id=id)
    instance.delete()
    return redirect('/ldm/ldm_meeting_update')

def ldm_forum(request,track=None):
    posted_data=LdmForum.objects.all()
    query=request.GET.get('forum-search')
    forum_form=LdmForumForm(data=request.POST )
    if query:
        posted_data=posted_data.filter(
                                    Q(track__icontains=query)|
                                    Q(title__icontains=query)|
                                    Q(question__icontains=query)
                                    )
    if request.method =='POST':
        if forum_form.is_valid():
            forum_form=forum_form.save(commit=False)
            forum_form.updated_by=request.session['user']
            forum_form.save()
            return redirect('/ldm/ldm_forum')
    else:
        paginator = Paginator(posted_data, 10) # Show 25 contacts per page
        page = request.GET.get('page')
        post = paginator.get_page(page)
        forum={"forum_form":forum_form,
                "posted_data":post,
                }
    return render(request,'ldm/ldm_forum.html',forum)

def edit_forum_content(request,id=None):
    instance=get_object_or_404(LdmForum,id=id)
    meeting_form=LdmForumForm(request.POST or None, instance=instance)
    meeting={"meeting_form":meeting_form,
                "posted_data":instance,
                }
    if meeting_form.is_valid():
        meeting=meeting_form.save(commit=False)
        meeting.updated_by=request.session['user']
        meeting.save()
        return redirect('/ldm/ldm_forum')
    else:
        return render(request,'ldm/editForumcontent.html',meeting)

def delete_forum_content(request, id=None):
    instance=get_object_or_404(LdmForum,id=id)
    instance.delete()
    return redirect('/ldm/ldm_forum')

def ldm_dashboard(request):
    s_date=request.GET.get('from_date')
    e_date=request.GET.get('to_date')
    track=request.GET.get('track')
    today=datetime.datetime.now()
    default_e_date=today-datetime.timedelta(days=30)
    default_s_date=datetime.datetime.strftime(today, '%m-%d-%Y')
    default_e_date=datetime.datetime.strftime(default_e_date, '%m-%d-%Y')
    default_s_date=datetime.datetime.strptime(default_s_date, '%m-%d-%Y')
    default_e_date=datetime.datetime.strptime(default_e_date, '%m-%d-%Y')
    if s_date is not None:
        if len(s_date)>0 and len(e_date)>0:
            user_s_date=datetime.datetime.strptime(s_date, '%m/%d/%Y')
            user_e_date=datetime.datetime.strptime(e_date, '%m/%d/%Y')

        if len(s_date)>0 and len(e_date)>0 and track=='all':
            ldm=dash.ldm_report(user_s_date,user_e_date)

        else:
            ldm=dash.ldm_report(default_e_date,default_s_date)
    else:
        ldm=dash.ldm_report(default_e_date,default_s_date)
    reports={
       "ldm_report":ldm,
        }
    return render (request,'ldm/ldm_dashboard.html',reports)

def format_date(date):
    return datetime.datetime.strptime(date, '%m/%d/%Y')

hda_forum/templates/ldm/editForumcontent.html
{% extends "base_pdc.html" %}

{% load static %}
{% block page %}
    {{ meeting_form.media }}
{% endblock page %}
{% block body %}

  <div class="row" style="background:inherit">
    <div class="col-lg-12">
      <nav class="navbar navbar-default bg nav-custom" style="z-index:10">
        <div class="container logout">
          <ul class="nav navbar-nav navbar-right log-bg">
            <li><a href="{% url 'desg_t18:login' %} "><span class="glyphicon glyphicon-user"></span>Logout</a></li>
          </ul>
        </div>
      </nav>
    </div>
  </div>
  <br><br><br><br><br><br>
<div class="row">
  <div class="col-md-3">
    <div class="collapse navbar-collapse navbar-ex1-collapse">
        <ul class="nav navbar-nav side-nav">
            <li>
                    <a href="{% url 'ldm:ldm_home' %}">
                        <i class="glyphicon glyphicon-home"></i>  LDM Home</a>
                </li>
                <li>
                    <a href="{% url 'ldm:ldm_dashboard' %}">
                        <i class="fa fa-fw fa-star"></i> LDM Dashboard</a>
                </li>
                <li>
                    <a href="{% url 'ldm:ldm_team' %}">
                        <i class="fa fa-fw fa-user"></i> PDC Team</a>
                </li>
                        <li>
                            <a href="{% url 'ldm:ldm_workflow' %}">
                                <i class="fa fa-fw fa-star"></i> LDM Work Flow</a>
                        </li>
                </li>
                <li>
                    <a href="#" data-toggle="collapse" data-target="#submenu-2">
                        <i class="fa fa-fw fa-star"></i> Discustions
                        <i class="fa fa-fw fa-angle-down pull-right"></i>
                    </a>
                    <ul id="submenu-2" class="collapse">
                        <li>
                            <a href="{% url 'ldm:ldm_meeting_update' %}">
                                <i class="fa fa-angle-double-right"></i> LDM Meeting Update</a>
                        </li>

                    </ul>
                </li>
                <li>
                    <a href="#" data-toggle="collapse" data-target="#submenu-3">
                        <i class="fa fa-fw fa-star"></i>LDM Automation
                        <i class="fa fa-fw fa-angle-down pull-right"></i>
                    </a>
                    <ul id="submenu-3" class="collapse">
                        <li>
                            <a href="{% url 'automation:ldm_automation' %}">
                                <i class="fa fa-angle-double-right"></i> Tool release Note</a>
                        </li>
                        <li>
                            <a href="{% url 'automation:ldm_automation_update' %}">
                                <i class="fa fa-angle-double-right"></i>Tool requirment Update</a>
                        </li>
                    </ul>
                </li>

                <li>
                    <a href="{% url 'ldm:ldm_forum' %}">
                        <i class="glyphicon glyphicon-book"></i> LDM Forum</a>
                </li>
        </ul>
        </div>
  </div>
  <div class="col-md-9">
    <br>
    <div class="container middle-content">
      <br><br>
      <h3 class="head text-center">Edit Forum contents</h3>
        <div class="jumbotron jumb">
        <form method="post">
          {% csrf_token %}
          <table >
          {% for field in meeting_form %}
          <tbody>
          <tr>
            <td>
              <label for="{{ field.label }}" style="display:inline-block;vertical-align:middle">{{ field.label_tag }}</label>
            </td>
            <td>
              {{ field }}
            </td>
          </tr>
          {% endfor %}
          </tbody>
        </table>
        <input class="btn btn-primary text-center custom-btn "type="submit" name="submit" value="Update">
        </form>
        </div>


      </div>
    </div>
  </div>
</div>

{% endblock %}

hda_forum/templates/ldm/ldm_forum.html
{% extends "base_pdc.html" %}

{% load crispy_forms_tags %}
{% load static %}
{% block page %}
    {{ forum_form.media }}
{% endblock page %}
{% block body %}

  <div class="row" style="background:inherit">
<div class="col-lg-12">
  <nav class="navbar navbar-default bg nav-custom" style="z-index:10">
    <div class="container logout">
      <ul class="nav navbar-nav navbar-right log-bg">
        <li><a href="http://127.0.0.1:8000/"><span class="glyphicon glyphicon-user"></span>Logout</a></li>
      </ul>
      <form class="navbar-form navbar-right" role="search">
                <div class="input-group">
                    <input class=" form-control" type="text" name="forum-search" placeholder="Search here">
                    <span class="input-group-btn">
                        <button type="submit" class="btn btn-default">
                            <span class="glyphicon glyphicon-search"></span>
                        </button>
                    </span>
                </div>
            </form>
    </div>
  </nav>
</div>
</div>
<br><br><br>
<div class="row">
  <div class="col-md-2">
    <div class="collapse navbar-collapse navbar-ex1-collapse">
        <ul class="nav navbar-nav side-nav">
           <li>
                    <a href="{% url 'ldm:ldm_home' %}">
                        <i class="glyphicon glyphicon-home"></i>  LDM Home</a>
                </li>
                <li>
                    <a href="{% url 'ldm:ldm_dashboard' %}">
                        <i class="fa fa-fw fa-star"></i> LDM Dashboard</a>
                </li>
                <li>
                    <a href="{% url 'ldm:ldm_team' %}">
                        <i class="fa fa-fw fa-user"></i> PDC Team</a>
                </li>
                        <li>
                            <a href="{% url 'ldm:ldm_workflow' %}">
                                <i class="fa fa-fw fa-star"></i> LDM Work Flow</a>
                        </li>
                </li>
                <li>
                    <a href="#" data-toggle="collapse" data-target="#submenu-2">
                        <i class="fa fa-fw fa-star"></i> Discustions
                        <i class="fa fa-fw fa-angle-down pull-right"></i>
                    </a>
                    <ul id="submenu-2" class="collapse">
                        <li>
                            <a href="{% url 'ldm:ldm_meeting_update' %}">
                                <i class="fa fa-angle-double-right"></i> LDM Meeting Update</a>
                        </li>

                    </ul>
                </li>
                <li>
                    <a href="#" data-toggle="collapse" data-target="#submenu-3">
                        <i class="fa fa-fw fa-star"></i>LDM Automation
                        <i class="fa fa-fw fa-angle-down pull-right"></i>
                    </a>
                    <ul id="submenu-3" class="collapse">
                        <li>
                            <a href="{% url 'automation:ldm_automation' %}">
                                <i class="fa fa-angle-double-right"></i> Tool release Note</a>
                        </li>
                        <li>
                            <a href="{% url 'automation:ldm_automation_update' %}">
                                <i class="fa fa-angle-double-right"></i>Tool requirment Update</a>
                        </li>
                    </ul>
                </li>

                <li>
                    <a href="{% url 'ldm:ldm_forum' %}">
                        <i class="glyphicon glyphicon-book"></i> LDM Forum</a>
                </li>
        </ul>
        </div>
  </div>
  <div class="col-md-10" >
    <div class="container">
        <h3 class="head text-center">LDM Knowledge Sharing Platform</h3>
      {% for post in posted_data %}
        <div class="jumbotron jumb">
        <h3 class="head meeting-content">Track : {{ post.track }} <small>{{ post.updated_date|timesince }}</small></h3>
        <p class="head meeting-content">{{ post.question }}</p>
        <p class="meeting-p">{{ post.answer|linebreaks }}</p>
        <p class="meeting-u">Updated by {{ post.updated_by }} on {{ post.updated_date }}</p>
        <br>
        <a class="btn btn-primary" href="{% url 'ldm:edit_forum_content' id=post.id %}">Edit</a>
        <a class="btn btn-primary" href="{% url 'ldm:delete_forum_content' id=post.id %}">Delete</a>
      </div>
      {% endfor %}
      <br><br>
      <!-- pagination goes here  -->
        <br><br>
        <div class="pagination">
          <span class="step-links">
              {% if posted_data.has_previous %}
                  <a href="?page=1">&laquo; first</a>
                  <a href="?page={{ posted_data.previous_page_number }}">previous</a>
              {% endif %}
          <span class="current">
            Page {{ posted_data.number }} of {{ posted_data.paginator.num_pages }}.
         </span>
            {% if posted_data.has_next %}
              <a href="?page={{ posted_data.next_page_number }}">next</a>
              <a href="?page={{ posted_data.paginator.num_pages }}">last &raquo;</a>
            {% endif %}
         </span>
       </div>

      <div class="jumbotron jumb">
      <form method="post">
      {% csrf_token %}
      {{forum_form|crispy}}

      <input class="btn btn-default btn-primary" type="submit" name="Submit">
      </form>
      </div>



  </div>
  </div>
</div>

{% endblock %}

hda_forum/templates/ldm/ldm_meetingupdates.html
{% extends "base_pdc.html" %}

{% load static %}
{% block page %}
    {{ meeting_form.media }}
{% endblock page %}
{% block body %}

  <div class="row" style="background:inherit">
    <div class="col-lg-12">
      <nav class="navbar navbar-default bg nav-custom" style="z-index:10">
        <div class="container logout">
          <ul class="nav navbar-nav navbar-right log-bg">
            <li><a href="http://127.0.0.1:8000/"><span class="glyphicon glyphicon-user"></span>Logout</a></li>
          </ul>
          <form class="navbar-form navbar-right" role="search">
                <div class="input-group">
                    <input class=" form-control" type="text" name="search" placeholder="Search here">
                    <span class="input-group-btn">
                        <button type="submit" class="btn btn-default">
                            <span class="glyphicon glyphicon-search"></span>
                        </button>
                    </span>
                </div>
            </form>
        </div>
      </nav>
    </div>
  </div>
  <br><br><br>
  <br><br><br>
<div class="row">
  <div class="col-md-3">
    <div class="collapse navbar-collapse navbar-ex1-collapse">
        <ul class="nav navbar-nav side-nav">
            <li>
                    <a href="{% url 'ldm:ldm_home' %}">
                        <i class="glyphicon glyphicon-home"></i>  LDM Home</a>
                </li>
                <li>
                    <a href="{% url 'ldm:ldm_dashboard' %}">
                        <i class="fa fa-fw fa-star"></i> LDM Dashboard</a>
                </li>
                <li>
                    <a href="{% url 'ldm:ldm_team' %}">
                        <i class="fa fa-fw fa-user"></i> PDC Team</a>
                </li>
                        <li>
                            <a href="{% url 'ldm:ldm_workflow' %}">
                                <i class="fa fa-fw fa-star"></i> LDM Work Flow</a>
                        </li>
                </li>
                <li>
                    <a href="#" data-toggle="collapse" data-target="#submenu-2">
                        <i class="fa fa-fw fa-star"></i> Discustions
                        <i class="fa fa-fw fa-angle-down pull-right"></i>
                    </a>
                    <ul id="submenu-2" class="collapse">
                        <li>
                            <a href="{% url 'ldm:ldm_meeting_update' %}">
                                <i class="fa fa-angle-double-right"></i> LDM Meeting Update</a>
                        </li>

                    </ul>
                </li>
                <li>
                    <a href="#" data-toggle="collapse" data-target="#submenu-3">
                        <i class="fa fa-fw fa-star"></i> LDM Automation
                        <i class="fa fa-fw fa-angle-down pull-right"></i>
                    </a>
                    <ul id="submenu-3" class="collapse">
                        <li>
                            <a href="{% url 'automation:ldm_automation' %}">
                                <i class="fa fa-angle-double-right"></i> Tool release Note</a>
                        </li>
                        <li>
                            <a href="{% url 'automation:ldm_automation_update' %}">
                                <i class="fa fa-angle-double-right"></i>Tool requirment Update</a>
                        </li>
                    </ul>
                </li>

                <li>
                    <a href="{% url 'ldm:ldm_forum' %}">
                        <i class="glyphicon glyphicon-book"></i> LDM Forum</a>
                </li>
        </ul>
        </div>
  </div>
  <div class="col-md-9">
    <br>
    <div class="">

    </div>
    <div class="container middle-content">

      <div class="text-center">
        <h3 class="head"> Meeting Updates</h3>
      </div>

      <!-- triage update content here  -->
      <div class="container">
        {% for post in posted_data %}
        <div class="jumbotron jumb">
        <h2 class="head meeting-content">{{ post.title }} <small>{{ post.updated_date|timesince}}</small></h2>
        <p class="meeting-p">{{ post.content }}</p>
        <p class="meeting-u">Updated By {{ post.updated_by}} on {{ post.updated_date}}</p>
        <br>
        <a class="btn btn-primary" href="{% url 'ldm:edit_meeting_content' id=post.id %}">Edit</a>
        <a class="btn btn-primary" href="{% url 'ldm:delete_meeting_content' id=post.id %}">Delete</a>
      </div>
        {% endfor %}
      </div>
      <!-- pagination goes here  -->
        <br><br>
        <div class="pagination">
          <span class="step-links">
              {% if posted_data.has_previous %}
                  <a href="?page=1">&laquo; first</a>
                  <a href="?page={{ posted_data.previous_page_number }}">previous</a>
              {% endif %}
          <span class="current">
            Page {{ posted_data.number }} of {{ posted_data.paginator.num_pages }}.
         </span>
            {% if posted_data.has_next %}
              <a href="?page={{ posted_data.next_page_number }}">next</a>
              <a href="?page={{ posted_data.paginator.num_pages }}">last &raquo;</a>
            {% endif %}
         </span>
       </div>

       <!-- pagination end here -->

      <!-- triage update form here  -->
      <br><br>
      <h3 class="head text-center">Meeting Update</h3>
        <div class="jumbotron jumb">
        <form method="post">
          {% csrf_token %}
          <table >
          {% for field in meeting_form %}
          <tbody>
          <tr>
            <td>
              <label for="{{ field.label }}" style="display:inline-block;vertical-align:middle">{{ field.label_tag }}</label>
            </td>
            <td>
              {{ field }}
            </td>
          </tr>
          {% endfor %}
          </tbody>
        </table>
        <input class="btn btn-primary text-center custom-btn "type="submit" name="submit" value="Submit">
        </form>
        </div>


      </div>
    </div>
  </div>
</div>

{% endblock %}