hda_forum/automation/urls.py
from django.urls import path
from automation import views
app_name='automation'


urlpatterns=[
	#Desg Automation url
	path('desg_automation/', views.desg_automation,name='desg_automation'),
	path('desg_automation_update/',views.desg_automation_update, name='desg_automation_update'),
	path('desg_automation/<id>/edit/', views.edit_desg_automation_content,name='edit_desg_automation_content'),
    path('desg_automation/<id>/delete/', views.delete_desg_automation_content,name='delete_desg_automation_content'),
	path('desg_automation_update/<id>/edit/', views.edit_desg_automation_update,name='edit_desg_automation_update'),
	path('desg_automation_update/<id>/delete/', views.delete_desg_automation_update,name='delete_desg_automation_update'),

	#Pdc Automation Url
	path('pdc_automation/', views.pdc_automation,name='pdc_automation'),
	path('pdc_automation_update/',views.pdc_automation_update, name='pdc_automation_update'),
	path('pdc_automation/<id>/edit/', views.edit_pdc_automation_content,name='edit_pdc_automation_content'),
    path('pdc_automation/<id>/delete/', views.delete_pdc_automation_content,name='delete_pdc_automation_content'),
	path('pdc_automation_update/<id>/edit/', views.edit_pdc_automation_update,name='edit_pdc_automation_update'),
	path('pdc_automation_update/<id>/delete/', views.delete_pdc_automation_update,name='delete_pdc_automation_update'),

	#Ldm Automation Url
	path('ldm_automation/', views.ldm_automation,name='ldm_automation'),
	path('ldm_automation_update/', views.ldm_automation_update, name='ldm_automation_update'),
	path('ldm_automation/<id>/edit/', views.edit_ldm_automation_content,name='edit_ldm_automation_content'),
    path('ldm_automation/<id>/delete/', views.delete_ldm_automation_content,name='delete_ldm_automation_content'),
	path('ldm_automation_update/<id>/edit/', views.edit_ldm_automation_update,name='edit_ldm_automation_update'),
	path('ldm_automation_update/<id>/delete/', views.delete_ldm_automation_update,name='delete_ldm_automation_update'),
]

hda_forum/desg_t18/urls.py
from django.urls import path
from desg_t18 import views
app_name='desg_t18'

urlpatterns=[
    #test
    path('test/',views.test, name='test'),
    #validate user
    path('login/', views.login, name='login'),
    path('register/', views.register, name='register'),
    path('reset_password/', views.reset_pass, name='change_pass'),
    #hda home
    path('home/', views.hda_home, name='hda_home'),
    path('team_view/', views.team_view, name='team_view'),
    #desg home
    path('desg_home/',views.desg_home, name='desg_home'),
    path('desg_team/',views.desg_team, name='desg_team'),
    #pc
    path('perform_check/',views.perform_check, name='pc'),
    path('pc_update/',views.pc_update, name='pc_update'),
    path('pc_update/<id>/edit/',views.edit_pc_update, name='edit_pc_update'),
    path('pc_update/<id>/delete/', views.delete_pc_update,name='delete_pc_update'),
    #gml
    path('gml_creation/',views.gml_creation, name='gml'),
    path('gml_update/',views.gml_update, name='gml_update'),
    path('gml_update/<id>/edit/',views.edit_gml_update, name='edit_gml_update'),
    path('gml_update/<id>/delete/', views.delete_gml_update,name='delete_gml_update'),
    #triage updates
    path('triage_update/',views.triage_update, name='triage_update'),
    path('triage_update/<id>/edit/',views.edit_triage_content, name='edit_triage_content'),
    path('triage_update/<id>/delete/', views.delete_triage_content,name='delete_triage_content'),
    #meeting update
    path('meeting_update/',views.meeting_update, name='meeting_update'),
    path('meeting_update/<id>/edit/', views.edit_meeting_content,name='edit_meeting_content'),
    path('meeting_update/<id>/delete/', views.delete_meeting_content,name='delete_meeting_content'),
    #forum updates
    path('forum/',views.forum, name='forum'),
    path('forum/<id>/edit/', views.edit_forum_content,name='edit_forum_content'),
    path('forum/<id>/delete/', views.delete_forum_content,name='delete_forum_content'),
    #dashboard
    path('desg_dashboard/', views.desg_dashboard,name='desg_dashboard'),
    path('hda_dashboard/',views.hda_dashboard, name='hda_dashboard'),
    
    
]

hda_forum/hda_forum/urls.py
"""hda_forum URL Configuration

The `urlpatterns` list routes URLs to views. For more information please see:
    https://docs.djangoproject.com/en/2.0/topics/http/urls/
"""
from django.contrib import admin
from django.urls import path,include
from django.conf import settings
from django.conf.urls.static import static
from desg_t18 import views
from desg_t18 import urls as desg_app
from automation import urls as automation_app
from pdc import urls as pdc_app
from ldm import urls as ldm_app

app_name='hda_forum'
urlpatterns = [
    path('', views.index, name='index'),
    path('pdc/', include(pdc_app)),
    path('desg/', include(desg_app)),
    path('ldm/', include(ldm_app)),
    path('automation/', include(automation_app)),
    path('admin/', admin.site.urls),


]

if settings.DEBUG:
    urlpatterns+= static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
    urlpatterns+= static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

hda_forum/ldm/urls.py
from django.urls import path
from ldm import views
app_name='ldm'

urlpatterns=[
    #pdc home
    path('ldm_home/',views.ldm_home, name='ldm_home'),
    path('ldm_team/',views.ldm_team, name='ldm_team'),
    path('ldm_workflow/',views.ldm_workflow, name='ldm_workflow'),
    #meeting update
    path('ldm_meeting_update/',views.ldm_meeting_update, name='ldm_meeting_update'),
    path('meeting_update/<id>/edit/', views.edit_meeting_content,name='edit_meeting_content'),
    path('meeting_update/<id>/delete/', views.delete_meeting_content,name='delete_meeting_content'),
    #forum updates
    path('ldm_forum/',views.ldm_forum, name='ldm_forum'),
    path('ldm_forum/<id>/edit/', views.edit_forum_content,name='edit_forum_content'),
    path('ldm_forum/<id>/delete/', views.delete_forum_content,name='delete_forum_content'),
    #dashboard
    path('ldm_dashboard/', views.ldm_dashboard,name='ldm_dashboard'),
    
    
]

hda_forum/templates/desg/forum.html
{% extends "base.html" %}

{% load crispy_forms_tags %}
{% load static %}
{% block page %}
    {{ forum_form.media }}
{% endblock page %}
{% block body %}

  <div class="row" style="background:inherit">
<div class="col-lg-12">
  <nav class="navbar navbar-default bg nav-custom" style="z-index:10">
    <div class="container logout">
      <ul class="nav navbar-nav navbar-right log-bg">
        <li><a href="http://127.0.0.1:8000/"><span class="glyphicon glyphicon-user"></span>Logout</a></li>
      </ul>
      <form class="navbar-form navbar-right" role="search">
                <div class="input-group">
                    <input class=" form-control" type="text" name="forum-search" placeholder="Search here">
                    <span class="input-group-btn">
                        <button type="submit" class="btn btn-default">
                            <span class="glyphicon glyphicon-search"></span>
                        </button>
                    </span>
                </div>
            </form>
    </div>
  </nav>
</div>
</div>
<br><br><br>
<div class="row">
  <div class="col-md-2">
    <div class="collapse navbar-collapse navbar-ex1-collapse">
        <ul class="nav navbar-nav side-nav">
          <li>
              <a href="{% url 'desg_t18:desg_home' %}"><i class="glyphicon glyphicon-home"></i>  DESG Home</a>
          </li>
          <li>
                    <a href="{% url 'desg_t18:desg_team' %}">
                        <i class="fa fa-fw fa-user"></i>DESG Team</a>
                </li>
          <li>
            <a href="#" data-toggle="collapse" data-target="#submenu-1"><i class="fa fa-fw fa-star"></i> DESG Work flow<i class="fa fa-fw fa-angle-down pull-right"></i></a>
              <ul id="submenu-1" class="collapse">
                  <li><a href="{% url 'desg_t18:pc' %}"><i class="fa fa-angle-double-right"></i> Perform check</a></li>
                  <li><a href="{% url 'desg_t18:gml' %}"><i class="fa fa-angle-double-right"></i> GML Creation</a></li>
              </ul>
          </li>
          <li>
            <a href="#" data-toggle="collapse" data-target="#submenu-2"><i class="fa fa-fw fa-star"></i>  Discustions <i class="fa fa-fw fa-angle-down pull-right"></i></a>
            <ul id="submenu-2" class="collapse">
              <li><a href="{% url 'desg_t18:triage_update' %}"><i class="fa fa-angle-double-right"></i> Triage Note</a></li>
              <li><a href="{% url 'desg_t18:meeting_update' %}"><i class="fa fa-angle-double-right"></i>Meeting updates</a></li>
            </ul>
          </li>
          <li>
            <a href="#" data-toggle="collapse" data-target="#submenu-3"><i class="fa fa-fw fa-star"></i>DESG Automation <i class="fa fa-fw fa-angle-down pull-right"></i></a>
            <ul id="submenu-3" class="collapse">
              <li><a href="{% url 'automation:desg_automation' %}"><i class="fa fa-angle-double-right"></i> Tool release Note</a></li>
              <li><a href="{% url 'automation:desg_automation_update' %}"><i class="fa fa-angle-double-right"></i>Tool requirment Update</a></li>
            </ul>
          </li>
              <li>
                  <a href="{% url 'desg_t18:desg_dashboard' %}"><i class="fa fa-fw fa-star"></i>DESG Dashboard</a>
              </li>
              <li>
                  <a href="{% url 'desg_t18:forum' %}"><i class="glyphicon glyphicon-book"></i>  Forum</a>
              </li>
        </ul>
        </div>
  </div>
  <div class="col-md-10" >
    <div class="container">
        <h3 class="head text-center">DESG Knowledge Sharing Platform</h3>
      {% for post in posted_data %}
        <div class="jumbotron jumb">
        <h3 class="head meeting-content">Track : {{ post.track }} <small>{{ post.updated_date|timesince }}</small></h3>
        <p class="head meeting-content">{{ post.question }}</p>
        <p class="meeting-p">{{ post.answer|linebreaks }}</p>
        <p class="meeting-u">Updated by {{ post.updated_by }} on {{ post.updated_date }}</p>
        <br>
        <a class="btn btn-primary" href="{% url 'desg_t18:edit_forum_content' id=post.id %}">Edit</a>
        <a class="btn btn-primary" href="{% url 'desg_t18:delete_forum_content' id=post.id %}">Delete</a>
      </div>
      {% endfor %}
      <br><br>
      <!-- pagination goes here  -->
        <br><br>
        <div class="pagination">
          <span class="step-links">
              {% if posted_data.has_previous %}
                  <a href="?page=1">&laquo; first</a>
                  <a href="?page={{ posted_data.previous_page_number }}">previous</a>
              {% endif %}
          <span class="current">
            Page {{ posted_data.number }} of {{ posted_data.paginator.num_pages }}.
         </span>
            {% if posted_data.has_next %}
              <a href="?page={{ posted_data.next_page_number }}">next</a>
              <a href="?page={{ posted_data.paginator.num_pages }}">last &raquo;</a>
            {% endif %}
         </span>
       </div>

      <div class="jumbotron jumb">
      <form method="post">
      {% csrf_token %}
      {{forum_form|crispy}}

      <input class="btn btn-default btn-primary" type="submit" name="Submit">
      </form>
      </div>



  </div>
  </div>
</div>

{% endblock %}

hda_forum/templates/desg/gml_update.html
{% extends "base.html" %} 
{% load crispy_forms_tags %}
 {% load static %}
  {% block page %} 
  {{ gml_update_form.media }} 
  {% endblock page %} 
  {% block body %}

<div class="row" style="background:inherit">
  <div class="col-lg-12">
    <nav class="navbar navbar-default bg nav-custom" style="z-index:10">
      <div class="container logout">
        <ul class="nav navbar-nav navbar-right log-bg">
          <li>
            <a href="http://127.0.0.1:8000/">
              <span class="glyphicon glyphicon-user"></span>Logout</a>
          </li>
        </ul>
        <form class="navbar-form navbar-right" role="search">
          <div class="input-group">
            <input class=" form-control" type="text" name="forum-search" placeholder="Search here">
            <span class="input-group-btn">
              <button type="submit" class="btn btn-default">
                <span class="glyphicon glyphicon-search"></span>
              </button>
            </span>
          </div>
        </form>
      </div>
    </nav>
  </div>
</div>
<br>
<br>
<br>
<br>
<br>
<br>
<div class="row">
  <div class="col-md-2">
    <div class="collapse navbar-collapse navbar-ex1-collapse">
      <ul class="nav navbar-nav side-nav">
        <li>
          <a href="{% url 'desg_t18:desg_home' %}">
            <i class="glyphicon glyphicon-home"></i>  DESG Home</a>
        </li>
        <li>
                    <a href="{% url 'desg_t18:desg_team' %}">
                        <i class="fa fa-fw fa-user"></i>DESG Team</a>
                </li>
        <li>
          <a href="#" data-toggle="collapse" data-target="#submenu-1">
            <i class="fa fa-fw fa-star"></i> DESG Work flow
            <i class="fa fa-fw fa-angle-down pull-right"></i>
          </a>
          <ul id="submenu-1" class="collapse">
            <li>
              <a href="{% url 'desg_t18:pc' %}">
                <i class="fa fa-angle-double-right"></i> Perform check</a>
            </li>
            <li>
              <a href="{% url 'desg_t18:gml' %}">
                <i class="fa fa-angle-double-right"></i> GML Creation</a>
            </li>
          </ul>
        </li>
        <li>
          <a href="#" data-toggle="collapse" data-target="#submenu-2">
            <i class="fa fa-fw fa-star"></i> Discustions
            <i class="fa fa-fw fa-angle-down pull-right"></i>
          </a>
          <ul id="submenu-2" class="collapse">
            <li>
              <a href="{% url 'desg_t18:triage_update' %}">
                <i class="fa fa-angle-double-right"></i> Triage Note</a>
            </li>
            <li>
              <a href="{% url 'desg_t18:meeting_update' %}">
                <i class="fa fa-angle-double-right"></i>Meeting updates</a>
            </li>
          </ul>
        </li>
        <li>
          <a href="#" data-toggle="collapse" data-target="#submenu-3">
            <i class="fa fa-fw fa-star"></i>DESG Automation
            <i class="fa fa-fw fa-angle-down pull-right"></i>
          </a>
          <ul id="submenu-3" class="collapse">
            <li>
              <a href="{% url 'automation:desg_automation' %}">
                <i class="fa fa-angle-double-right"></i> Tool release Note</a>
            </li>
            <li>
              <a href="{% url 'automation:desg_automation_update' %}">
                <i class="fa fa-angle-double-right"></i>Tool requirment Update</a>
            </li>
          </ul>
        </li>
        <li>
          <a href="{% url 'desg_t18:desg_dashboard' %}">
            <i class="fa fa-fw fa-star"></i>DESG Dashboard</a>
        </li>
        <li>
          <a href="{% url 'desg_t18:forum' %}">
            <i class="glyphicon glyphicon-book"></i> Forum</a>
        </li>

      </ul>
    </div>
  </div>
  <div class="col-md-10">
    <div class="container">
      {% for post in posted_data %}
      <div class="jumbotron jumb">

        <h3 class="head meeting-content">{{ post.title }}
          <small>{{ post.updated_date|timesince }}</small>
        </h3>
        <p class="meeting-p">{{ post.content }}</p>
        <p class="meeting-u">Updated by {{ post.updated_by }} on {{ post.updated_date}}</p>
        <br>
        <a class="btn btn-primary" href="{% url 'desg_t18:edit_gml_update' id=post.id %}">Edit</a>
        <a class="btn btn-primary" href="{% url 'desg_t18:delete_gml_update' id=post.id %}">Delete</a>
      </div>
      {% endfor %}
      <br>
      <br>
      <!-- pagination goes here  -->
      <br>
      <br>
      <div class="pagination">
        <span class="step-links">
          {% if posted_data.has_previous %}
          <a href="?page=1">&laquo; first</a>
          <a href="?page={{ posted_data.previous_page_number }}">previous</a>
          {% endif %}
          <span class="current">
            Page {{ posted_data.number }} of {{ posted_data.paginator.num_pages }}.
          </span>
          {% if posted_data.has_next %}
          <a href="?page={{ posted_data.next_page_number }}">next</a>
          <a href="?page={{ posted_data.paginator.num_pages }}">last &raquo;</a>
          {% endif %}
        </span>
      </div>

      <div class="jumbotron jumb">
        <form method="post">
          {% csrf_token %} {{gml_update_form|crispy}}

          <input class="btn btn-default btn-primary" type="submit" name="Submit">
        </form>
      </div>



    </div>
  </div>
</div>

{% endblock %}

hda_forum/templates/desg/meetingupdates.html
{% extends "base.html" %}

{% load static %}
{% block page %}
    {{ meeting_form.media }}
{% endblock page %}
{% block body %}

  <div class="row" style="background:inherit">
    <div class="col-lg-12">
      <nav class="navbar navbar-default bg nav-custom" style="z-index:10">
        <div class="container logout">
          <ul class="nav navbar-nav navbar-right log-bg">
            <li><a href="http://127.0.0.1:8000/"><span class="glyphicon glyphicon-user"></span>Logout</a></li>
          </ul>
          <form class="navbar-form navbar-right" role="search">
                <div class="input-group">
                    <input class=" form-control" type="text" name="search" placeholder="Search here">
                    <span class="input-group-btn">
                        <button type="submit" class="btn btn-default">
                            <span class="glyphicon glyphicon-search"></span>
                        </button>
                    </span>
                </div>
            </form>
        </div>
      </nav>
    </div>
  </div>
  <br><br><br>
  <br><br><br>
<div class="row">
  <div class="col-md-3">
    <div class="collapse navbar-collapse navbar-ex1-collapse">
        <ul class="nav navbar-nav side-nav">
          <li>
              <a href="{% url 'desg_t18:desg_home' %}"><i class="glyphicon glyphicon-home"></i>  DESG Home</a>
          </li>
          <li>
                    <a href="{% url 'desg_t18:desg_team' %}">
                        <i class="fa fa-fw fa-user"></i>DESG Team</a>
                </li>
          <li>
            <a href="#" data-toggle="collapse" data-target="#submenu-1"><i class="fa fa-fw fa-star"></i> DESG Work flow<i class="fa fa-fw fa-angle-down pull-right"></i></a>
              <ul id="submenu-1" class="collapse">
                  <li><a href="{% url 'desg_t18:pc' %}"><i class="fa fa-angle-double-right"></i> Perform check</a></li>
                  <li><a href="{% url 'desg_t18:gml' %}"><i class="fa fa-angle-double-right"></i> GML Creation</a></li>
              </ul>
          </li>
          <li>
            <a href="#" data-toggle="collapse" data-target="#submenu-2"><i class="fa fa-fw fa-star"></i>  Discustions <i class="fa fa-fw fa-angle-down pull-right"></i></a>
            <ul id="submenu-2" class="collapse">
              <li><a href="{% url 'desg_t18:triage_update' %}"><i class="fa fa-angle-double-right"></i> Triage Note</a></li>
              <li><a href="{% url 'desg_t18:meeting_update' %}"><i class="fa fa-angle-double-right"></i>Meeting updates</a></li>
            </ul>
          </li>
          <li>
            <a href="#" data-toggle="collapse" data-target="#submenu-3"><i class="fa fa-fw fa-star"></i>DESG Automation <i class="fa fa-fw fa-angle-down pull-right"></i></a>
            <ul id="submenu-3" class="collapse">
              <li><a href="{% url 'automation:desg_automation' %}"><i class="fa fa-angle-double-right"></i> Tool release Note</a></li>
              <li><a href="{% url 'automation:desg_automation_update' %}"><i class="fa fa-angle-double-right"></i>Tool requirment Update</a></li>
            </ul>
          </li>
              <li>
                  <a href="{% url 'desg_t18:desg_dashboard' %}"><i class="fa fa-fw fa-star"></i>DESG Dashboard</a>
              </li>
              <li>
                  <a href="{% url 'desg_t18:forum' %}"><i class="glyphicon glyphicon-book"></i>  Forum</a>
              </li>

        </ul>
        </div>
  </div>
  <div class="col-md-9">
    <br>
    <div class="">

    </div>
    <div class="container middle-content">

      <div class="text-center">
        <h3 class="header"> Meeting Updates</h3>
      </div>

      <!-- triage update content here  -->
      <div class="container">
        {% for post in posted_data %}
        <div class="jumbotron jumb">
        <h2 class="head meeting-content">{{ post.title }} <small>{{ post.updated_date|timesince}}</small></h2>
        <p class="meeting-p">{{ post.content }}</p>
        <p class="meeting-u">Updated By {{ post.updated_by}} on {{ post.updated_date}}</p>
        <br>
        <a class="btn btn-primary" href="{% url 'desg_t18:edit_meeting_content' id=post.id %}">Edit</a>
        <a class="btn btn-primary" href="{% url 'desg_t18:delete_meeting_content' id=post.id %}">Delete</a>
      </div>
        {% endfor %}
      </div>
      <!-- pagination goes here  -->
        <br><br>
        <div class="pagination">
          <span class="step-links">
              {% if posted_data.has_previous %}
                  <a href="?page=1">&laquo; first</a>
                  <a href="?page={{ posted_data.previous_page_number }}">previous</a>
              {% endif %}
          <span class="current">
            Page {{ posted_data.number }} of {{ posted_data.paginator.num_pages }}.
         </span>
            {% if posted_data.has_next %}
              <a href="?page={{ posted_data.next_page_number }}">next</a>
              <a href="?page={{ posted_data.paginator.num_pages }}">last &raquo;</a>
            {% endif %}
         </span>
       </div>

       <!-- pagination end here -->

      <!-- triage update form here  -->
      <br><br>
      <h3 class="header text-center">Meeting Update</h3>
        <div class="jumbotron jumb">
        <form method="post">
          {% csrf_token %}
          <table >
          {% for field in meeting_form %}
          <tbody>
          <tr>
            <td>
              <label for="{{ field.label }}" style="display:inline-block;vertical-align:middle">{{ field.label_tag }}</label>
            </td>
            <td>
              {{ field }}
            </td>
          </tr>
          {% endfor %}
          </tbody>
        </table>
        <input class="btn btn-primary text-center custom-btn "type="submit" name="submit" value="Submit">
        </form>
        </div>


      </div>
    </div>
  </div>
</div>

{% endblock %}

hda_forum/templates/desg/pc_update.html
{% extends "base.html" %}

{% load crispy_forms_tags %}
{% load static %}
{% block page %}
    {{ pc_update_form.media }}
{% endblock page %}
{% block body %}

  <div class="row" style="background:inherit">
<div class="col-lg-12">
  <nav class="navbar navbar-default bg nav-custom" style="z-index:10">
    <div class="container logout">
      <ul class="nav navbar-nav navbar-right log-bg">
        <li><a href="http://127.0.0.1:8000/"><span class="glyphicon glyphicon-user"></span>Logout</a></li>
      </ul>
      <form class="navbar-form navbar-right" role="search">
                <div class="input-group">
                    <input class=" form-control" type="text" name="forum-search" placeholder="Search here">
                    <span class="input-group-btn">
                        <button type="submit" class="btn btn-default">
                            <span class="glyphicon glyphicon-search"></span>
                        </button>
                    </span>
                </div>
            </form>
    </div>
  </nav>
</div>
</div>
<br><br><br>
<div class="row">
  <div class="col-md-2">
    <div class="collapse navbar-collapse navbar-ex1-collapse">
        <ul class="nav navbar-nav side-nav">
          <li>
              <a href="{% url 'desg_t18:desg_home' %}"><i class="glyphicon glyphicon-home"></i>  DESG Home</a>
          </li>
          <li>
                    <a href="{% url 'desg_t18:desg_team' %}">
                        <i class="fa fa-fw fa-user"></i>DESG Team</a>
                </li>
          <li>
            <a href="#" data-toggle="collapse" data-target="#submenu-1"><i class="fa fa-fw fa-star"></i> DESG Work flow<i class="fa fa-fw fa-angle-down pull-right"></i></a>
              <ul id="submenu-1" class="collapse">
                  <li><a href="{% url 'desg_t18:pc' %}"><i class="fa fa-angle-double-right"></i> Perform check</a></li>
                  <li><a href="{% url 'desg_t18:gml' %}"><i class="fa fa-angle-double-right"></i> GML Creation</a></li>
              </ul>
          </li>
          <li>
            <a href="#" data-toggle="collapse" data-target="#submenu-2"><i class="fa fa-fw fa-star"></i>  Discustions <i class="fa fa-fw fa-angle-down pull-right"></i></a>
            <ul id="submenu-2" class="collapse">
              <li><a href="{% url 'desg_t18:triage_update' %}"><i class="fa fa-angle-double-right"></i> Triage Note</a></li>
              <li><a href="{% url 'desg_t18:meeting_update' %}"><i class="fa fa-angle-double-right"></i>Meeting updates</a></li>
            </ul>
          </li>
          <li>
            <a href="#" data-toggle="collapse" data-target="#submenu-3"><i class="fa fa-fw fa-star"></i>DESG Automation <i class="fa fa-fw fa-angle-down pull-right"></i></a>
            <ul id="submenu-3" class="collapse">
              <li><a href="{% url 'automation:desg_automation' %}"><i class="fa fa-angle-double-right"></i> Tool release Note</a></li>
              <li><a href="{% url 'automation:desg_automation_update' %}"><i class="fa fa-angle-double-right"></i>Tool requirment Update</a></li>
            </ul>
          </li>
              <li>
                  <a href="{% url 'desg_t18:desg_dashboard' %}"><i class="fa fa-fw fa-star"></i>DESG Dashboard</a>
              </li>
              <li>
                  <a href="{% url 'desg_t18:forum' %}"><i class="glyphicon glyphicon-book"></i>  Forum</a>
              </li>

        </ul>
        </div>
  </div>
  <div class="col-md-10" >
    <div class="container">
        <h3 class="head text-center">Perform Check Updates</h3>
      {% for post in posted_data %}
        <div class="jumbotron jumb">

        <h3 class="head meeting-content">{{ post.title }} <small>{{ post.updated_date|timesince }}</small></h3>
        <p class="meeting-p">{{ post.content }}</p>
        <p class="meeting-u">Updated by {{ post.updated_by }} on {{ post.updated_date}}</p>
        <br>
        <a class="btn btn-primary" href="{% url 'desg_t18:edit_pc_update' id=post.id %}">Edit</a>
        <a class="btn btn-primary" href="{% url 'desg_t18:delete_pc_update' id=post.id %}">Delete</a>
      </div>
      {% endfor %}
      <br><br>
      <!-- pagination goes here  -->
        <br><br>
        <div class="pagination">
          <span class="step-links">
              {% if posted_data.has_previous %}
                  <a href="?page=1">&laquo; first</a>
                  <a href="?page={{ posted_data.previous_page_number }}">previous</a>
              {% endif %}
          <span class="current">
            Page {{ posted_data.number }} of {{ posted_data.paginator.num_pages }}.
         </span>
            {% if posted_data.has_next %}
              <a href="?page={{ posted_data.next_page_number }}">next</a>
              <a href="?page={{ posted_data.paginator.num_pages }}">last &raquo;</a>
            {% endif %}
         </span>
       </div>

      <div class="jumbotron jumb">
      <form method="post">
      {% csrf_token %}
      {{pc_update_form|crispy}}

      <input class="btn btn-default btn-primary" type="submit" name="Submit">
      </form>
      </div>



  </div>
  </div>
</div>

{% endblock %}